apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result.service
    app: test-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app
    app: test-voting-app
