apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: test-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: test-voting-app
  template:
    metadata:
      name: voting-app
      labels:
        name: voting-app
        app: test-voting-app
    spec:
      containers:
        - name: voting
          image: ayobrown/votingapp
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
